### ISSUE TITLE
Vertical spacings in title page

### ISSUE THREAD

**Issue by fanurs** [amunn/msu-thesis#23]
## Describe the problem

Currently, we have:
<img width="361" alt="image" src="https://github.com/amunn/msu-thesis/assets/21100851/613b8a56-1620-4cd8-ac84-a3fcd0eb3a3e">
https://github.com/amunn/msu-thesis/blob/c48d95fba1dc0631ed2fac8afdd83edcc6676f44/samples/MSU-thesis-testfile.pdf

But MSU requires two empty lines after "A DISSERTATION", and one empty line after "for the degree of".
<img width="563" alt="image" src="https://github.com/amunn/msu-thesis/assets/21100851/c0374140-74c9-4198-9d1f-2e7b92e8ad05">
https://grad.msu.edu/sites/default/files/content/etd/Sample%20Pages%20with%20TOC.pdf#page=11

**Comment by amunn** [comment]
Thanks for the report. Is this based on complaints from the thesis office, or just your reading of the requirements? Many students have submitted with the current version with no complaints.

**Comment by fanurs** [comment]
I have not checked with other students. This is what I received from the ETD office just now at around 11.
> TITLE PAGE: Add a space between the heading “A DISSERTATION” and “Submitted to” this will bring down the paragraph that starts with “Submitted to” to the correct margin. Then you will have to delete a space after the line “for the degree of” and your degree granting unit to keep your degree granting unit and year at the correct margin.

They also included the link above with the sample page. I can check with other students too.

**Comment by amunn** [comment]
No, that's fine. They're very inconsistent with what they notice.
