### ISSUE TITLE
Bibliography title page and LoF/LoT spacing issues

### ISSUE THREAD

**Issue by anthoak13** [amunn/msu-thesis#25]
The addition of this `\clearpage` https://github.com/amunn/msu-thesis/blob/60b6c2b91c7d0031d96e2ea4c0d1ac456e5f09d2/msu-thesis.cls#L813 seems to have made the bibliography have a title page, which the thesis office was not happy about.

They are also complaining about the spacing between the heading `LIST OF TABLES` and the first entry in the list claiming there is too much space. They also complain about the spacing being inconsistent between entries. I suspect these are somehow related problems. It seems as if there is more spacing between the entries corresponding to different chapters (i.e. space between table 2.4/2.5 is the same as the space between 3.1/.3.2 but the space between table 2.5/3.1 is larger than the typical spacing).

**Comment by amunn** [comment]
Please did you read the guidelines for raising issues? Please include a minimal document that shows the problem.

**Comment by anthoak13** [comment]
Minimal working example:
```
\documentclass[]{msu-thesis}

\usepackage{caption}
\DeclareCaptionType{test}

\begin{document}

\frontmatter
\SingleSpacing
\tableofcontents* % table of contents will not be listed in the TOC
\clearpage
\listoftables % comment this out if you have no tables
\clearpage
\listoffigures % comment this out if you have no figures

\mainmatter
\chapter{chapter 1}

\begin{table*}[ht!]
  \begin{center}
    \caption{Selected gas properties of CF$_4$ at running conditions.}
    \label{tab:gasProperties}
    \begin{tabular}{|c|c|c|c|c|} 
   
    \end{tabular}
  \end{center}
\end{table*}

\begin{table}[ht!]
  \begin{center}
    \caption{Selected properties of stable $^{208}$Pb beams used to test detectors.}
    \label{tab:stableBeam}
    \begin{tabular}{|c|c|c|c|c|} 
    
    \end{tabular}
  \end{center}
\end{table}

\chapter{Chapter 2}
\begin{table*}[ht!]
  \begin{center}
    \caption{Selected gas properties of CF$_4$ at running conditions.}
    \label{tab:gasProperties2}
    \begin{tabular}{|c|c|c|c|c|} 
   
    \end{tabular}
  \end{center}
\end{table*}

\begin{table}[ht!]
  \begin{center}
    \caption{Selected properties of stable $^{208}$Pb beams used to test detectors.}
    \label{tab:stableBeam2}
    \begin{tabular}{|c|c|c|c|c|} 
    
    \end{tabular}
  \end{center}
\end{table}
\end{document}
```


Result:
![image](https://github.com/amunn/msu-thesis/assets/13934511/45207406-179f-471a-82e9-6fef1341dd60)

The issue seems to be the declaration of a new caption type (`\DeclareCaptionType{test}`) in line 4. If that is commented out then the spacing is correct
![image](https://github.com/amunn/msu-thesis/assets/13934511/ea0c49cf-a9cb-4616-9487-99e11f2f0cdb)

**Comment by amunn** [comment]
Thanks. Strictly speaking this is not a class problem but a `caption` problem. I'll take a look though to see what can be done.

**Comment by amunn** [comment]
Don't use the `caption` methods for defining new float types. See §5.6.3 of the documentation for an example of how to set up a new floating environment.
