### ISSUE TITLE
Missing page count on copy write page

### ISSUE THREAD

**Issue by ani-mal** [amunn/msu-thesis#5]
### Description 

I just submitted my thesis to ProQuest, and I received feedback that my page count was incorrect. 

> Dedication Page: Previous pages were to be counted but not numbered, making this page “iv”. Please change the page > number on this page.
> • ***PRELIMINARY PAGES: Your preliminary pages are currently incorrectly numbered. 

My dedication page was numbered "iii" instead of "iv". 

### Fix Solution 

- Add the following line `\addtocounter{page}{1}` inside the make copy write page:
```
% make the copyright page
\newcommand*{\makecopyrightpage}{%
	\pagestyle{plain}
	\clearpage
	\thispagestyle{empty}
	\vspace*{7in}
	{\raggedleft Copyright by\\\MakeUppercase{\theauthor}\\\thedate\\}% Author now uppercase 6/5/12
	\clearpage
    \addtocounter{page}{1}}
```
https://github.com/amunn/msu-thesis/blob/108ea5ff49d1e79349ca63937dcd1671a6e2d390/msu-thesis.cls#L446

**Comment by amunn** [comment]
Hi thanks for the bug report. Since this has been in place for many years without a problem I'd like to understand a bit better how it arose. Can you tell me exactly what you had in the `\frontmatter` pages in your thesis? (Actual content isn't relevant, just which parts).  Thanks

**Comment by ani-mal** [comment]
That is what I got:

```
\begin{document}
\frontmatter
\maketitlepage

\begin{publicabstract}
\input{MSU Thesis/Abstract/PublicAbstract}
\end{publicabstract}
```

**Comment by amunn** [comment]
Thanks, but this doesn't match with what your initial bug report shows. The note from the thesis office mentions a dedication page, and your fix suggests fixing the copyright page. Can you show me all of the things you have between `\frontmatter` and `\mainmatter` in your document?

**Comment by ani-mal** [comment]
```
\begin{document}
\frontmatter
\maketitlepage

\begin{publicabstract}
\input{MSU Thesis/Abstract/PublicAbstract}
\end{publicabstract}


\clearpage
\makecopyrightpage
\makededicationpage
\clearpage

\chapter*{Acknowledgements}
\input{MSU Thesis/Acknowledgement/Acknowledgement}

\clearpage
\SingleSpacing
\tableofcontents* % ToC will not appear in the table of contents
\clearpage
\listoftables
\clearpage
\listoffigures
\clearpage
\listoflistings
\clearpage

\input{MSU Thesis/KeyToAbbreviations/Abbreviations}

\mainmatter
```

**Comment by ani-mal** [comment]
The bug report was fixed by altering the `.cls` what I have provided on the past comments are chunks of the .tex

**Comment by amunn** [comment]
Thanks a lot. Before I accept the fix I need to understand the actual source of the problem. I suspect that it reflects a change in what is/is not supposed to be numbered relative to previous years.

**Comment by ani-mal** [comment]
@amunn that could indeed be a relative new change, indeed. That was also my thought when I ran into it. 

But with this fix, my dissertation got accepted by ProQuest.

**Comment by amunn** [comment]
This problem was caused by the fact that you had no abstract in your document, only the public abstract. The `{publicabstract}` environment produces  unnumbered and uncounted pages, and should be used only in *addition* to a regular abstract, which you didn't have. Since the thesis office requires the two abstracts to be formatted the same way, there's no way to tell that the public abstract was not the regular abstract. I'll update the documentation to explain this more carefully, and for future versions add some checks that obligatory components are in fact there.
